database:
  default:
    link: "mysql:root:123456@tcp(127.0.0.1:3306)/demo?charset=utf8mb4&parseTime=True&loc=Local"
    debug: true
    dryRun: false
    maxIdle: 10
    maxOpen: 100
  bootstrap:
    user: "root"
    pass: "123456"
    host: "127.0.0.1"
    port: 3306
    name: "demo"
